#!/bin/bash
#
# description: System-V Init-Script for Logwatcher
#
# Get function from functions library
. /etc/init.d/functions.sh

# Start the service logwatcher
start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --quiet --exec /usr/bin/logwatcher -- -d
	touch /var/lock/logwatcher
	eend $?
}

# Restart the service logwatcher
stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --quiet --exec /usr/bin/logwatcher
	rm -f /var/lock/logwatcher
	eend $?
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
