#!/bin/bash
#
# description: System-V Init-Script for Logwatcher
#
# Get function from functions library
. /etc/init.d/functions

# Start the service logwatcher
start() {
        initlog -c "echo -n Starting logwatcher server: "
        /usr/bin/logwatcher -d
        ### Create the lock file ###
        touch /var/lock/logwatcher
        success $"logwatcher server startup"
        echo
}

# Restart the service logwatcher
stop() {
        initlog -c "echo -n Stopping logwatcher server: "
        killproc logwatcher
        ### Now, delete the lock file ###
        rm -f /var/lock/logwatcher
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status logwatcher
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
